### ISSUE TITLE
GUI Features

### ISSUE THREAD

**Issue by gravesjohnr** [johnbartkiw/mycroft-skill-iheartradio#3]
John,
FYI, I created a fork to add GUI components to display the station logo/description and provide a play/pause button.
Feel free to include or not.
-John

**Comment by gravesjohnr** [comment]
I can move this to a pull request if you want.  I've just added a bit more code to show current track playing.

**Comment by johnbartkiw** [comment]
Hi John,
A PR would be most helpful. I'm not sure exactly what you mean by GUI components either. Is this for the Mark II? I only have a Mark I so I'm not familiar with the latest and greatest. :)

Either way I'm happy to merge in a PR for it.

-j

**Comment by gravesjohnr** [comment]
I'm not at my office right now, but I'll take a photo to show.  The GUI should work with the mark II or any mycroft with a display.  I don't think the mark I supports the UI...  Anyway, it displays the radio station artwork/description as well as the current song artwork/artist/etc...

**Comment by johnbartkiw** [comment]
I've merged the PR. I don't have a Mark II so I'm trusting your testing. :)
